Repository compwiz32/PSADHealth, pull requests merged in 2019-03, with the labels that each got.

#36 Module load cleanup
  Public/Test-ADServices.ps1
  Public/Test-ExternalTimeSync.ps1
  Public/Test-InternalTimeSync.ps1
Labels: bug

#42 move export from psm1 to psd1
  PSADHealth.psd1
  PSADHealth.psm1
Labels: bug, enhancement

#44 Config file fixes
  Public/ADConfig.json
  Public/Get-ADConfig.ps1
Labels: bug, enhancement

#46 Several fixes here to make the config experience great.
  PSADHealth.psd1
  Public/Get-ADConfig.ps1
  Public/Set-PSADHealthConfig.ps1
Labels: enhancement

#48 Updated scripts using a config to use the new Get-ADConfig cmdlet.
  Public/Get-ADLastBackupDate.ps1
  Public/Test-ADObjectReplication.ps1
  Public/Test-ADReplication.ps1
  Public/Test-ADServices.ps1
  Public/Test-ExternalTimeSync.ps1
  Public/Test-InternalTimeSync.ps1
  Public/Test-SYSVOL-Replication.ps1
Labels: enhancement

#50 Update Get-ADConfig. Fix references.
  Public/Get-ADConfig.ps1
  Public/Get-ADLastBackupDate.ps1
  Public/Test-ADObjectReplication.ps1
  Public/Test-ADReplication.ps1
  Public/Test-ADServices.ps1
  Public/Test-ExternalTimeSync.ps1
  Public/Test-InternalTimeSync.ps1
  Public/Test-SYSVOL-Replication.ps1
Labels: enhancement

#53 Basically a complete rewrite of Set cmdlet.
  Public/Set-PSADHealthConfig.ps1
Labels: bug, enhancement

#57 Bug fixes
  Config/ADConfig.json
  PSADHealth.psm1
  Private/New-SlackPost.ps1
  Private/Send-AlertCleared.ps1
  Private/Send-Mail.ps1
  Public/Get-ADConfig.ps1
  Public/Get-ADLastBackupDate.ps1
  Public/Get-DCDiskSpace.ps1
  Public/Set-PSADHealthConfig.ps1
  Public/Test-ADObjectReplication.ps1
  Public/Test-ADReplication.ps1
  Public/Test-ADServices.ps1
  Public/Test-DCsOnline.ps1
  Public/Test-ExternalDNSServers.ps1
  Public/Test-InternalTimeSync.ps1
  Public/Test-SRVRecords.ps1
  Public/Test-SYSVOL-Replication.ps1
Labels: enhancement
